services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8080"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
